### PR TITLE
fix cms git list

### PR DESCRIPTION
**Pull request by jpfleischer**
cms git list has been updated, because it doesnt work and is defunct and broken.

try this:
`cms git list laszewski --forks=yes --archived=yes`

or

`cms git list user_that_does_not_exist`
`ERROR: User user_that_does_not_exist does not exist!`

or

`cms git list jpfleischer`
defaults to jpfleischer's repos that are NOT forks and that are NOT archived
```bash
CodePathSITE
DataWrangling
HelloThere
Lab1
Lab2
MDCstudentSIMULATOR
REU-DataScienceProgram
REU-MachineLearningAlgorithms
REU-Python
stapmoshun
['CodePathSITE', 'DataWrangling', 'HelloThere', 'Lab1', 'Lab2', 'MDCstudentSIMULATOR', 'REU-DataScienceProgram', 'REU-MachineLearningAlgorithms', 'REU-Python', 'stapmoshun']

Written list of repos to C:\Users\Sledgehammer/.cloudmesh/git/repo-list-jpfleischer.txt
# Timer: 1.2443s Load: 0.0850s git list jpfleischer
(ENV3)
Sledgehammer@Sledgehammer MINGW64 ~/desktop
```

### CODE REVIEW

**Comment by jpfleischer** [comment]
there is another way.
my question is, would you like to use the json file, or use Github python module?

method two that uses Github python module:
```python
        if arguments.list:
            '''
            m = Manager()

            m.list(arguments.MATCH)
            '''

            is_getting_forks = str_bool(arguments.forks)
            is_getting_archived = str_bool(arguments.archived)

            my_dir = os.path.expanduser('~/.cloudmesh/git/')
            if not os.path.isdir(my_dir):
                os.mkdir(my_dir)

            handle = arguments.HANDLE
            g = Github()
            user = g.get_user(handle)
            repos = user.get_repos()

            repos_list = []
            for repo in repos:
                if not is_getting_forks:
                    if repo.fork is True:
                        continue
                if not is_getting_archived:
                    if repo.archived is True:
                        continue
                repos_list.append(repo.name)

            print(repos_list)

            with open(f'{my_dir}repo-list-{arguments.HANDLE}.txt', 'w') as file:
                for item in repos_list:
                    file.write("%s\n" % item)
            Console.ok(f'\nWritten list of repos to {my_dir}repo-list-{arguments.HANDLE}.txt')
            file.close()
```

**Comment by laszewsk** [comment]
i have not looked much in the implementation of the old code that is used to create student directories nor the list.

I have only looked at cli gh which did not exist when I wrote the original code.

gh has list for organizations and repos.

the goal is to create some cache that includes all of them and then work on the cache (e.g. a file) to do the pull.
do not make this more complicated then needed.
if you need help I can be consulted.
the goal is a solution ... to backining up all organizations and all repos in these organizations given a username

**Comment by laszewsk** [comment]
if github module works fine, if gh cli should be used fine. whatever works and whatever we can create the cache with.

**Comment by laszewsk** [comment]
so goal is 

cms git --refresh # redirects automatically to ~/cloudmesh/git/repo-list.txt
cms git clone --all # uses automatically ~/cloudmesh/git/repo-list.txt

**Pull request closed without merging**
